name: Sanity
on:
  pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
        timeout-minutes: 5
      - name: Run tests
        run: npm run test
        timeout-minutes: 10
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
        timeout-minutes: 5
      - name: Run ESLint
        run: npm run eslint
        timeout-minutes: 10
